name: final-project-gr-2-backend
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: WindyBoss/final-project-gr-2-backend
  name: final-project-gr-2-backend